import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

// These files are generated by the build_runner
part 'database.g.dart';

// Define the Categories table
class Categories extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().unique()();
  IntColumn get color => integer()(); // Store color as an integer (e.g., 0xFFF44336)
}

// Define the Transactions table
@DataClassName('TransactionItem')
class Transactions extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get description => text().withLength(min: 1, max: 100)();
  IntColumn get categoryId => integer().references(Categories, #id)();
  DateTimeColumn get transactionDate => dateTime()();
  RealColumn get amount => real()();
  BoolColumn get isExpense => boolean().withDefault(const Constant(true))();
}

@DriftDatabase(tables: [Categories, Transactions])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  // --- Queries for Categories ---
  Future<List<Category>> getAllCategories() => select(categories).get();
  Future<int> insertCategory(CategoriesCompanion category) => into(categories).insert(category);

  // --- Queries for Transactions ---
  Future<List<TransactionItem>> getAllTransactions() => select(transactions).get();
  // Watch transactions for a specific month
  Stream<List<TransactionItem>> watchTransactionsInMonth(DateTime month) {
    // Start of the selected month (e.g., October 1st, 00:00:00)
    final startOfMonth = DateTime(month.year, month.month, 1);

    // Start of the NEXT month (e.g., November 1st, 00:00:00)
    final startOfNextMonth = DateTime(month.year, month.month + 1, 1);

    return (select(transactions)
    // Use two separate conditions combined with the '&' (AND) operator
      ..where((t) =>
      t.transactionDate.isBiggerOrEqual(Constant(startOfMonth)) &
      t.transactionDate.isSmallerThan(Constant(startOfNextMonth)))
      ..orderBy([(t) =>
          OrderingTerm(expression: t.transactionDate, mode: OrderingMode.desc)]))
        .watch();
  }
  Future<int> insertTransaction(TransactionsCompanion transaction) => into(transactions).insert(transaction);
  Future<bool> updateTransaction(TransactionsCompanion transaction) => update(transactions).replace(transaction);
  Future<int> deleteTransaction(int id) => (delete(transactions)..where((t) => t.id.equals(id))).go();
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    return NativeDatabase(file);
  });
}